name: Trigger Docker Builds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-folder-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      workflows: write 

    steps:
      - name: Trigger Calculator-project1 workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Calculator-project1/.github/workflows/docker.yml',
              ref: 'main'
            });

      - name: Trigger Temperature_converter_project_9 workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Temperature_converter_project_9/.github/workflows/docker.yml',
              ref: 'main'
            });

      - name: Trigger Library-Management-System workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Library-Management-System/.github/workflows/docker.yml',
              ref: 'main'
            });

      - name: Trigger Todo _list_project3 workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Todo _list_project3/.github/workflows/docker.yml',
              ref: 'main'
            });

      - name: Trigger Rock_game workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Rock_game/.github/workflows/docker.yml',
              ref: 'main'
            });

      - name: Trigger Student Grade Tracker workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Student Grade Tracker/.github/workflows/docker.yml',
              ref: 'main'
            });

      - name: Trigger Simple-Chatbot-project-10 workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Simple-Chatbot-project-10/.github/workflows/docker.yml',
              ref: 'main'
            });

      - name: Trigger Guessing_game_java _project2 workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Guessing_game_java _project2/.github/workflows/docker.yml',
              ref: 'main'
            });